### ISSUE TITLE
Allow disconnecting of events

### ISSUE THREAD

**Issue by jmesrje** [Uncontained0/Red#5]
It would be nice to allow the disconnection of events, as well as functions such as Once and Wait. I would use this for my framework under a wrapper if these features existed.

**Comment by jackhexed** [comment]
Only one function can be assigned to an event at a time, this function can be removed by calling `Net:On("EventName", nil)`. 

This is intentional design, the overhead of full events is not needed in networking as having multiple listeners to a single networked event is almost never used, and in most cases is bad design.

If this feature is ***really*** needed you can create it yourself.
```lua
local Event = Red.Signal.new()

Net:On("EventName", function(...)
	Event:Fire(...)
end)```
